# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: narajaon <marvin@42.fr>                    +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2017/04/11 18:59:25 by narajaon          #+#    #+#              #
#    Updated: 2017/10/19 16:41:10 by narajaon         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

NAME = libft.a

SRC = \
	  ft_atoi_base.c \
	  ft_abs.c \
	  ft_putchar.c \
	  ft_putstr.c \
	  ft_putnbr.c \
	  ft_strcmp.c \
	  ft_strlen.c \
	  ft_strncmp.c \
	  ft_strlen.c \
	  ft_strdup.c \
	  ft_strstr.c \
	  ft_strcat.c \
	  ft_strncat.c \
	  ft_strlcat.c \
	  ft_strcpy.c \
	  ft_strncpy.c \
	  ft_strnstr.c \
	  ft_strchr.c \
	  ft_strrchr.c \
	  ft_isalpha.c \
	  ft_isdigit.c \
	  ft_isprint.c \
	  ft_isalnum.c \
	  ft_isascii.c \
	  ft_isspace.c \
	  ft_tolower.c \
	  ft_toupper.c \
	  ft_itoa.c \
	  ft_atoi.c \
	  ft_memset.c \
	  ft_bzero.c \
	  ft_memcpy.c \
	  ft_memccpy.c \
	  ft_memmove.c \
	  ft_memchr.c \
	  ft_memcmp.c \
	  ft_putendl.c \
	  ft_putchar_fd.c \
	  ft_putstr_fd.c \
	  ft_putendl_fd.c \
	  ft_putnbr_fd.c \
	  ft_memalloc.c \
	  ft_memdel.c \
	  ft_strnew.c \
	  ft_strdel.c \
	  ft_strclr.c \
	  ft_striter.c \
	  ft_striteri.c \
	  ft_strmap.c \
	  ft_strmapi.c \
	  ft_strequ.c \
	  ft_strnequ.c \
	  ft_strsub.c \
	  ft_strjoin.c \
	  ft_strsplit.c \
	  ft_strtrim.c \
	  ft_lstnew.c \
	  ft_lstdelone.c \
	  ft_lstdel.c \
	  ft_lstadd.c \
	  ft_lstiter.c \
	  ft_lstmap.c \
	  ft_isc.c \
	  ft_isnu.c \
	  ft_islower.c \
	  ft_isupper.c \
	  ft_isspace.c \
	  ft_iseven.c \
	  ft_print_words_tables.c \
	  get_next_line.c \
	  free_tab.c \
	  ft_lstback.c \
	  ft_lstadd_back.c \
	  ft_strndup.c \
	  ft_strtrimc.c \
	  ft_print_tab.c \
	  ft_tab_dup.c \
	  ft_tab_size.c \
	  ft_print_lst.c \
	  free_tab_str.c \
	  ft_lstpop.c \
	  free_str.c


CC = -Wall -Werror -Wextra

OBJ = $(SRC:.c=.o)

HEADER = libft.h

GNL = get_next_line.h

all: $(NAME)

$(NAME): $(SRC) $(HEADER) $(GNL)
		@gcc -c $(SRC)
		@ar rc $(NAME) $(OBJ)
		@ranlib $(NAME)
		@echo "[libft] Compiling $(NAME)\033[92m OK\033[0m"

clean:
		@echo "[libft] Deleting:\033[33m *.o\033[0m"
		@rm -f *.o

fclean: clean
		@echo "[libft] Deleting:\033[33m $(NAME)\033[0m"
		@rm -f $(NAME)

re: fclean all
